# Generated by Django 5.2.4 on 2025-07-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="pyment_date",
            field=models.DateField(help_text="Укажите дату совершения платежа", verbose_name="Дата оплаты"),
        ),
    ]
