# Generated by Django 5.2.4 on 2025-07-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_pyment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="pyment_date",
            new_name="payment_date",
        ),
    ]
