# Generated by Django 5.2.4 on 2025-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("users", "0004_rename_pyment_date_payments_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateTimeField(help_text="Укажите дату совершения платежа", verbose_name="Дата оплаты"),
        ),
    ]
