# Generated by Django 5.2.4 on 2025-07-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
