# Generated by Django 5.2.4 on 2025-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Статус платежа"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe сесии ID"),
        ),
    ]
