# Generated by Django 5.2.4 on 2025-07-30 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payments_payment_link_payments_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now, verbose_name="Дата последнего входа"
            ),
            preserve_default=False,
        ),
    ]
