# Generated by Django 5.2.4 on 2025-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_course_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите стоимость курса",
                max_digits=10,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите стоимость урока",
                max_digits=10,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
    ]
