# Generated by Django 5.2.4 on 2025-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe цена ID"),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe продукт ID"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe цена ID"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe продукт ID"),
        ),
    ]
