# Generated by Django 5.2.4 on 2025-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_stripe_price_id_course_stripe_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость курса",
                max_digits=10,
                verbose_name="Стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость урока",
                max_digits=10,
                verbose_name="Стоимость",
            ),
        ),
    ]
